### ISSUE TITLE
Echoing Reprimand with Resounding Clarity.

### ISSUE THREAD

**Issue by Cluuey** [parnic/ice-hud#16]
Hi Parnic,
I was wondering if it's possible to have the combo point display highlight all of the Anima Charged combo points when you're using the new legendary?
It makes 2, 3, 4 & 5 Anima Charged, currently IceHUD only shows one at a time starting with the lowest one. 

Playing Subtlety using that two point one is very annoying but during Shadow Blades, the 3m CD, it's impossible.

**Comment by parnic** [comment]
Yes, acquiring the legendary was the blocker for me :).

**Comment by Cluuey** [comment]
I've used the alpha for a few days now and had no problems, so I think we can say you made it work.

Thanks for being awesome for still sorting this out even though you're not playing. :-)
