### ISSUE TITLE
Blizzard frames bleeding through on 9.2

### ISSUE THREAD

**Issue by lranders** [parnic/ice-hud#19]
The blizzard player, pet and target frames are bleeding through when hidden.

A reload will re-hide, but only temporarily.

Addon build is **1.13.11**

**Comment by parnic** [comment]
Does this happen with only IceHUD enabled and no other mods (as a temporary diagnostic step)?

Can you attach your SavedVariables\IceHUD.lua please?

**Comment by lranders** [comment]
Settings attached:
[IceHUD.lua.txt](https://github.com/parnic/ice-hud/files/8304069/IceHUD.lua.txt)

The issue seems to happen when exiting vehicle mode or after watching a cutscene.

Will try to run WoW with IceHUD only later tonight.

**Comment by lranders** [comment]
Ok, I ran with only the 2 IceHUD addons active and to my dismay,
everything I did worked fine ... until I opened once of the chests in Zereth Mortis,
you know, the ones that requires Pocopoc to start one of the mini-games.

Right after completing one of those, the player frame popped into view.
Fearing that it was a fluke, I tried it again on 2 other characters, with the same result; frame visible.

It should be noted that the ones I opened had daily quests attached to it.
I don't know if that has any significance, but I wanted you to know.

**Comment by parnic** [comment]
Thanks. So it sounds like another addon is causing the issue with vehicles and other things you mentioned. I have no idea what these chests are you're talking about, but will take a look.

**Comment by lranders** [comment]
Please disregard my first comment from a few days ago; I was writing from memory.
Vehicles and pet battles do _not_ seem to provoke the issue, based on playing this weekend.

On the other hand, the Protolock Box Puzzles are reliably able to reproduce the issue.

Here's a description, way better than anything I could write myself:
https://www.wowhead.com/news/new-protolock-box-puzzles-in-zereth-mortis-patch-9-2-eternitys-end-325204

I hope this clears up the confusion and leads to a fix, soonish.

**Comment by Cluuey** [comment]
I came here to mention this too, I thought it was those Box Puzzles triggering it but hadn't found the time to isolate it.
BugGrabber captured this error so I'm pasting it here.
Hopefully it helps.

```
1x [ADDON_ACTION_BLOCKED] AddOn 'IceHUD' tried to call the protected function 'Boss1TargetFrame:SetPoint()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetPoint'
[string "@FrameXML\UIParent.lua"]:3485: in function `UIParentManageFramePositions'
[string "@FrameXML\UIParent.lua"]:2739: in function <FrameXML\UIParent.lua:2726>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3536: in function <FrameXML\UIParent.lua:3534>
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@FrameXML\MainMenuBar.lua"]:161: in function `MainMenuBarVehicleLeaveButton_Update'
[string "@FrameXML\MainMenuBar.lua"]:135: in function <FrameXML\MainMenuBar.lua:134>

Locals:
Skipped (In Encounter)```

**Comment by parnic** [comment]
> I came here to mention this too, I thought it was those Box Puzzles triggering it but hadn't found the time to isolate it. BugGrabber captured this error so I'm pasting it here. Hopefully it helps.
> 
> ```
> 1x [ADDON_ACTION_BLOCKED] AddOn 'IceHUD' tried to call the protected function 'Boss1TargetFrame:SetPoint()'.
> [string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
> [string "=[C]"]: in function `SetPoint'
> [string "@FrameXML\UIParent.lua"]:3485: in function `UIParentManageFramePositions'
> [string "@FrameXML\UIParent.lua"]:2739: in function <FrameXML\UIParent.lua:2726>
> [string "=[C]"]: in function `SetAttribute'
> [string "@FrameXML\UIParent.lua"]:3536: in function <FrameXML\UIParent.lua:3534>
> [string "=[C]"]: in function `UIParent_ManageFramePositions'
> [string "@FrameXML\MainMenuBar.lua"]:161: in function `MainMenuBarVehicleLeaveButton_Update'
> [string "@FrameXML\MainMenuBar.lua"]:135: in function <FrameXML\MainMenuBar.lua:134>
> 
> Locals:
> Skipped (In Encounter)
> ```

IceHUD never calls `Boss1TargetFrame:SetPoint()`, so this is most likely being blamed on IceHUD because of how WoW shared libraries work. If you disable every addon except IceHUD and BugGrabber, does this still pop up?

**Comment by parnic** [comment]
I was able to make this happen locally and am hopeful that the latest commit fixes the issue. Please try alpha version 1.13.12-alpha1 and let me know how it looks.
