### ISSUE TITLE
Any chance of updating a version for WoW Classic?

### ISSUE THREAD

**Issue by theredsox** [parnic/ice-hud#2]
I've used IceHud as long as I can remember, but so far I have not heard of anyone looking to update a version for WoW Classic. From the limited I know Classic is running on a modified 8.0.1 API. So mod devs are starting with their 8.0.1 branches and then tweaking for what has changed. Most say it's been pretty easy for retail mods as they are so close to what Classic is running anyway. If you have any interest, it would be amazing to have a Classic version.

Cheers,
~Brandon

**Comment by parnic** [comment]
I won't be playing WoW classic and don't really have time to build and test a version of the mod for Classic. I'd gladly accept user contributions for this. All old releases are on Curse as well as github, so should be able to pull down an 8.0 version of the mod and see how it does.
