### ISSUE TITLE
Errors with 10.0 game client

### ISSUE THREAD

**Issue by l3uGsY** [parnic/ice-hud#24]
Curse won't let me post this
It errors out,
Do you have an other method of donating besides Paypal, like Patreon.

**Comment by parnic** [comment]
It posted successfully, and I replied: https://www.wowace.com/projects/ice-hud?comment=6981

Sure, you can use [Ko-fi](https://ko-fi.com/parnic) or [Venmo](https://venmo.com/parnic) and I'm getting setup with [Github sponsors](https://github.com/sponsors/parnic) at the moment.

10.0 development branch: https://github.com/parnic/ice-hud/tree/10.0
Dragonflight development branch: https://github.com/parnic/ice-hud/tree/dragonflight

**Comment by parnic** [comment]
v1.14.0-alpha1 has been released with 10.0 support. Please report additional specific issues with that build separately.
