### ISSUE TITLE
Live version: No DK runes showing

### ISSUE THREAD

**Issue by AddonWhiner** [parnic/ice-hud#29]
I had this on the live version when the prepatch hit. Using the alpha version brought them back. The updated live version is still missing them. The only error I get when loading IceHUD on live is #27 and that doesn't seem related.

**Comment by parnic** [comment]
Can you clarify what you mean by "live version"? Specific version numbers would help here.

The only released build of IceHUD that functions on 10.0 is v1.14.0-alpha1. All previous versions cannot work with the new game client.

**Comment by parnic** [comment]
Update dates look expected
<img width="700" alt="image" src="https://user-images.githubusercontent.com/888126/198373159-79401027-3129-4190-ae5e-a8f115a3c723.png">
