### ISSUE TITLE
Add ability to hide Blizzard cast bar

### ISSUE THREAD

**Issue by Malivil** [parnic/ice-hud#30]
Hi =)

First of all let me say I've used IceHUD for years and I love it so thank you for all the work you've put in.

Is there a way to hide the default casting bar when using the IceHUD casting bar? If not, is that something that can be added as an option?

Thanks in advance

**Comment by parnic** [comment]
/icehud -> Module Settings -> Cast Bar -> Show default cast bar

**Comment by Malivil** [comment]
Hmm, I had that unchecked but I think it was a problem with the 9.2.7 version on 10.0
I updated to the 10.0 alpha and it's working now

Thanks!
