### ISSUE TITLE
having issues/errors in the maw targeting mobs while doing the missing baron quest

### ISSUE THREAD

**Issue by MelchiorGaspar** [parnic/ice-hud#33]
"The hunt for the baron" quest with the meter in the top middle..

targeting any mobs triggers it..
WoW-retail 
had to disable IceHUD for now... :(
this is on my Human paladin.
errors below.

4x IceHUD/modules/ClassPowerCounter.lua:877: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: in function `unpack'
[string "@IceHUD/modules/ClassPowerCounter.lua"]:877: in function `SetupRuneTexture'
[string "@IceHUD/modules/ClassPowerCounter.lua"]:758: in function `SetDisplayMode'
[string "@IceHUD/modules/ClassPowerCounter.lua"]:738: in function `CreateFrame'
[string "@IceHUD/modules/ClassPowerCounter.lua"]:512: in function `UpdateRunePower'
[string "@IceHUD/modules/DragonridingVigor.lua"]:64: in function `UpdateRunePower'
[string "@IceHUD/modules/ClassPowerCounter.lua"]:407: in function `Redraw'
[string "@IceHUD/modules/ClassPowerCounter.lua"]:959: in function `?'
[string "@AutoProfitX2/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...tX2/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AutoProfitX2/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...tX2/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@AutoProfitX2/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@AutoProfitX2/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...dOns/AutoProfitX2/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

37x IceHUD/modules/ClassPowerCounter.lua:619: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: in function `unpack'
[string "@IceHUD/modules/ClassPowerCounter.lua"]:619: in function `SetRuneCoords'
[string "@IceHUD/modules/ClassPowerCounter.lua"]:567: in function `UpdateRunePower'
[string "@IceHUD/modules/DragonridingVigor.lua"]:64: in function `?'
[string "@AutoProfitX2/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...tX2/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AutoProfitX2/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...tX2/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@AutoProfitX2/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@AutoProfitX2/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...dOns/AutoProfitX2/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by MelchiorGaspar** [comment]
IceHUD v1.14.15

**Comment by MelchiorGaspar** [comment]
I re-enabled it after that part of the game in the MAW... and it seems to be working fine again...
If I recall correctly this is not the first time this has happened.. :-(

**Comment by parnic** [comment]
This is fixed in the latest Alpha release. I'll get that promoted to a full release

**Comment by MelchiorGaspar** [comment]
ok, thx for the reply and fix Parnic.

**Comment by parnic** [comment]
Fixed in v1.14.16.

**Comment by MelchiorGaspar** [comment]
👍
