### ISSUE TITLE
Dragonriding Vigor not displaying

### ISSUE THREAD

**Issue by justisb** [parnic/ice-hud#34]
Patch 10.1 was released today, and the Dragonriding Vigor graphics are no longer displaying for IceHUD. 

I've confirmed that the mount spell IDs have not changed, so effectively `DragonridingVigor.prototype:CheckShouldShow` returns true, but I have not investigated further.

**Comment by parnic** [comment]
Thanks, I will take a look at this today.

**Comment by parnic** [comment]
I tagged this issue in the wrong commit. It was actually fixed in 24c45f320fc66e289db5f24bd8e2d45cfd96f8a3
