### ISSUE TITLE
new update just broke the addon :( on classic era

### ISSUE THREAD

**Issue by Hsjsjsjsmsk** [parnic/ice-hud#37]
new update just broke the addon :( on classic era

**Comment by parnic** [comment]
Broken how? Error messages? Something specific not functioning?

**Comment by Hsjsjsjsmsk** [comment]
not working at all :(

**Comment by Hsjsjsjsmsk** [comment]
they just update the game to dragonblight client btw

**Comment by parnic** [comment]
I'm on classic-era game version 1.14.4 and latest IceHUD (v1.14.25) is working.

<img width="1147" alt="image" src="https://github.com/parnic/ice-hud/assets/888126/5b5def30-726b-45c5-98d5-fea261aefb3d">

**Comment by Hsjsjsjsmsk** [comment]
will try it soon ty <3

**Comment by parnic** [comment]
Check the login screen to see if IceHUD is disabled for being out of date maybe? I can push a TOC update, but nothing appears broken to me.
