### ISSUE TITLE
WoW-retail (v11.0)-prepatch, IceHUD bugs

### ISSUE THREAD

**Issue by MelchiorGaspar** [parnic/ice-hud#40]
I got a continuous stream of IceHUD bugs errors via BugSack popups...
and other bugs with IceHUD, I will post below
.
Hope it can be fixed for WOW-retail v11.0.2 I think.

375x IceHUD/libs/LibDogTag-3.0-20240509050323/Events.lua:711: IceHUD/libs/LibDogTag-3.0/Events.lua:565: attempt to call global 'GetMouseFocus' (a nil value)
[string "=[C]"]: ?
[string "@IceHUD/libs/LibDogTag-3.0-20240509050323/Events.lua"]:711: in function <IceHUD/libs/LibDogTag-3.0/Events.lua:702>

Locals:
(*temporary) = false
(*temporary) = "IceHUD/libs/LibDogTag-3.0/Events.lua:565: attempt to call global 'GetMouseFocus' (a nil value)"
--------------------------------------

1x IceHUD/IceHUD.lua:351: attempt to index field 'IceCore' (a nil value)
[string "@IceHUD/IceHUD.lua"]:351: in function <IceHUD/IceHUD.lua:349>
[string "=[C]"]: ?
[string "@AutoProfitX2/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...dOns/AutoProfitX2/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@AutoProfitX2/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@AutoProfitX2/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...dOns/AutoProfitX2/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 modules = <table> {
 }
 baseName = "IceHUD"
 CurrTagVersion = 3
 UnitGroupRolesReturnsRoleString = true
 debugging = false
 defaultModuleState = true
 DeathKnightUnholyFrostRunesSwapped = false
 PerTargetComboPoints = false
 PerPowerEventsExist = false
 hooks = <table> {
 }
 EventExistsSpellcastInterruptible = true
 SpellFunctionsReturnRank = false
 enabledState = true
 ShouldUpdateTargetHealthEveryTick = false
 EventExistsPlayerPetChanged = false
 WowClassicWrath = false
 defaultModuleLibraries = <table> {
 }
 WowMain = true
 Location = "Interface\AddOns\IceHUD"
 EventExistsUnitMaxPower = true
 WowClassicCataclysm = false
 name = "IceHUD"
 GetSpellInfoReturnsFunnel = false
 orderedModules = <table> {
 }
 validCustomModules = <table> {
 }
 EventExistsUnitDynamicFlags = false
 HasShellGame = "Ready"
 validBarList = <table> {
 }
 UnitPowerEvent = "UNIT_POWER_UPDATE"
 HasCataloging = "Cataloger's Camera"
 CatalogingSpellIDs = <table> {
 }
 EventExistsGroupRosterUpdate = true
 ShellGameSpellID = 271571
 UsesUIPanelButtonTemplate = true
 WowClassic = false
 CanShowTargetCasting = true
 EventExistsPlayerComboPoints = false
 SupportsHealPrediction = true
 CanHookDestroyTotem = false
 CanTrackOtherUnitBuffs = true
 EventExistsPetBarChanged = false
 WowVer = 110000
 WowClassicBC = false
 EventExistsUnitComboPoints = false
 CanTrackGCD = true
 EventExistsUnitHealthFrequent = false
}
isFirst = nil
(*temporary) = nil
(*temporary) = <table> {
 modules = <table> {
 }
 baseName = "IceHUD"
 CurrTagVersion = 3
 UnitGroupRolesReturnsRoleString = true
 debugging = false
 defaultModuleState = true
 DeathKnightUnholyFrostRunesSwapped = false
 PerTargetComboPoints = false
 PerPowerEventsExist = false
 hooks = <table> {
 }
 EventExistsSpellcastInterruptible = true
 SpellFunctionsReturnRank = false
 enabledState = true
 ShouldUpdateTargetHealthEveryTick = false
 EventExistsPlayerPetChanged = false
 WowClassicWrath = false
 defaultModuleLibraries = <table> {
 }
 WowMain = true
 Location = "Interface\AddOns\IceHUD"
 EventExistsUnitMaxPower = true
 WowClassicCataclysm = false
 name = "IceHUD"
 GetSpellInfoReturnsFunnel = false
 orderedModules = <table> {
 }
 validCustomModules = <table> {
 }
 EventExistsUnitDynamicFlags = false
 HasShellGame = "Ready"
 validBarList = <table> {
 }
 UnitPowerEvent = "UNIT_POWER_UPDATE"
 HasCataloging = "Cataloger's Camera"
 CatalogingSpellIDs = <table> {
 }
 EventExistsGroupRosterUpdate = true
 ShellGameSpellID = 271571
 UsesUIPanelButtonTemplate = true
 WowClassic = false
 CanShowTargetCasting = true
 EventExistsPlayerComboPoints = false
 SupportsHealPrediction = true
 CanHookDestroyTotem = false
 CanTrackOtherUnitBuffs = true
 EventExistsPetBarChanged = false
 WowVer = 110000
 WowClassicBC = false
 EventExistsUnitComboPoints = false
 CanTrackGCD = true
 EventExistsUnitHealthFrequent = false
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'IceCore' (a nil value)"

**Comment by MelchiorGaspar** [comment]
2x IceHUD/IceElement.lua:50: attempt to call method 'Register' (a nil value)
[string "@IceHUD/IceElement.lua"]:50: in function `init'
[string "@IceHUD/IceBarElement.lua"]:27: in function `init'
[string "@IceHUD/IceUnitBar.lua"]:31: in function `init'
[string "@IceHUD/modules/PlayerMana.lua"]:35: in function `init'
[string "@IceHUD/IceCore.lua"]:12: in function `new'
[string "@IceHUD/modules/PlayerMana.lua"]:502: in main chunk

Locals:
self = <table> {
 scalingEnabled = false
 elementName = "PlayerMana"
 alpha = 1
}
name = "PlayerMana"
skipRegister = nil
(*temporary) = nil
(*temporary) = <table> {
 modules = <table> {
 }
 CurrTagVersion = 3
 UnitGroupRolesReturnsRoleString = true
 debugging = false
 defaultModuleState = true
 DeathKnightUnholyFrostRunesSwapped = false
 PerTargetComboPoints = false
 PerPowerEventsExist = false
 hooks = <table> {
 }
 EventExistsSpellcastInterruptible = true
 SpellFunctionsReturnRank = false
 enabledState = true
 ShouldUpdateTargetHealthEveryTick = false
 EventExistsPlayerPetChanged = false
 WowClassicWrath = false
 defaultModuleLibraries = <table> {
 }
 WowMain = true
 Location = "Interface\AddOns\IceHUD"
 EventExistsUnitMaxPower = true
 WowClassicCataclysm = false
 name = "IceHUD"
 GetSpellInfoReturnsFunnel = false
 orderedModules = <table> {
 }
 validCustomModules = <table> {
 }
 EventExistsUnitDynamicFlags = false
 HasShellGame = "Ready"
 validBarList = <table> {
 }
 UnitPowerEvent = "UNIT_POWER_UPDATE"
 HasCataloging = "Cataloger's Camera"
 CatalogingSpellIDs = <table> {
 }
 EventExistsGroupRosterUpdate = true
 ShellGameSpellID = 271571
 UsesUIPanelButtonTemplate = true
 WowClassic = false
 CanShowTargetCasting = true
 EventExistsPlayerComboPoints = false
 SupportsHealPrediction = true
 CanHookDestroyTotem = false
 CanTrackOtherUnitBuffs = true
 EventExistsPetBarChanged = false
 WowVer = 110000
 WowClassicBC = false
 EventExistsUnitComboPoints = false
 CanTrackGCD = true
 EventExistsUnitHealthFrequent = false
}
(*temporary) = <table> {
 scalingEnabled = false
 elementName = "PlayerMana"
 alpha = 1
}
(*temporary) = "attempt to call method 'Register' (a nil value)"
IceHUD = <table> {
 modules = <table> {
 }
 CurrTagVersion = 3
 UnitGroupRolesReturnsRoleString = true
 debugging = false
 defaultModuleState = true
 DeathKnightUnholyFrostRunesSwapped = false
 PerTargetComboPoints = false
 PerPowerEventsExist = false
 hooks = <table> {
 }
 EventExistsSpellcastInterruptible = true
 SpellFunctionsReturnRank = false
 enabledState = true
 ShouldUpdateTargetHealthEveryTick = false
 EventExistsPlayerPetChanged = false
 WowClassicWrath = false
 defaultModuleLibraries = <table> {
 }
 WowMain = true
 Location = "Interface\AddOns\IceHUD"
 EventExistsUnitMaxPower = true
 WowClassicCataclysm = false
 name = "IceHUD"
 GetSpellInfoReturnsFunnel = false
 orderedModules = <table> {
 }
 validCustomModules = <table> {
 }
 EventExistsUnitDynamicFlags = false
 HasShellGame = "Ready"
 validBarList = <table> {
 }
 UnitPowerEvent = "UNIT_POWER_UPDATE"
 HasCataloging = "Cataloger's Camera"
 CatalogingSpellIDs = <table> {
 }
 EventExistsGroupRosterUpdate = true
 ShellGameSpellID = 271571
 UsesUIPanelButtonTemplate = true
 WowClassic = false
 CanShowTargetCasting = true
 EventExistsPlayerComboPoints = false
 SupportsHealPrediction = true
 CanHookDestroyTotem = false
 CanTrackOtherUnitBuffs = true
 EventExistsPetBarChanged = false
 WowVer = 110000
 WowClassicBC = false
 EventExistsUnitComboPoints = false
 CanTrackGCD = true
 EventExistsUnitHealthFrequent = false
}

**Comment by MelchiorGaspar** [comment]
1x IceHUD/modules/PlayerHealth.lua:1424: attempt to call method 'OutOfCombatWrapper' (a nil value)
[string "@IceHUD/modules/PlayerHealth.lua"]:1424: in main chunk

Locals:
L = <table> {
 If your class power is not full (or not empty in the case of Holy Power) then the module will always be displayed on your screen using the In Combat alpha setting. Otherwise it will fade to the OOC alpha when you leave combat. = "If your class power is not full (or not empty in the case of Holy Power) then the module will always be displayed on your screen using the In Combat alpha setting. Otherwise it will fade to the OOC alpha when you leave combat."
 Bar vertical offset = "Bar vertical offset"
 When the player is in one of the chosen shapeshift forms the bar will be shown, otherwise it will be hidden. = "When the player is in one of the chosen shapeshift forms the bar will be shown, otherwise it will be hidden."
 This will hide the entire mod when interacting with a barbershop. = "This will hide the entire mod when interacting with a barbershop."
 Show Minimap Icon = "Show Minimap Icon"
 Sets the height of this module. = "Sets the height of this module."
 Item to track = "Item to track"
 No decoration = "No decoration"
 Potential SnD time bar alpha = "Potential SnD time bar alpha"
 Determines the bar width compared to the whole texture width = "Determines the bar width compared to the whole texture width"
 Whether or not to show incoming heals as a lighter-colored bar on top of your current health (requires LibHealComm-4.0 or official patch 4.0) = "Whether or not to show incoming heals as a lighter-colored bar on top of your current health (requires LibHealComm-4.0 or official patch 4.0)"
 Buffs / row = "Buffs / row"
 Flash when ready = "Flash when ready"
 Only show in groups = "Only show in groups"
 Self Display Mode = "Self Display Mode"
 Module type: = "Module type:"
 Debuff grow direction = "Debuff grow direction"
 What this bar should do whenever the player is the TargetOfTarget = "What this bar should do whenever the player is the TargetOfTarget"
 Change color when not in range = "Change color when not in range"
 Raid Icon X Offset = "Raid Icon X Offset"
 BG Alpha in combat = "BG Alpha in combat"
 Controls which direction the bar fills up. With this checked, the bar will fill opposite from normal (e.g. for health: 0% at the top, 100% at the bottom). = "Controls which direction the bar fills up. With this checked, the bar will fill opposite from normal (e.g. for health: 0% at the top, 100% at the bottom)."
 Contextual Background = "Contextual Background"
 Lower text visible = "Lower text visible"
 Pulse when full = "Pulse when full"
 Debuff horizontal offset = "Debuff horizontal offset"
 Icon Settings = "Icon Settings"
 IceHUD Bar Texture = "IceHUD Bar Texture"
 Font = "Font"
 DogTag-formatted string to use for the right side of the bar.

Type /dogtag for a list of available tags.

Remember to press Accept after filling out this box or it will not save. = "DogTag-formatted string to use for the right side of the bar.

Type /dogtag for a list of available tags.

Remember to press Accept after filling out this box or it will not save."
 Settings related to positioning and alpha = "Settings related to positioning and alpha"
 Hides Blizzard Player frame and disables all events related to it = "Hides Blizzard Player frame and disables all events related to it"
 PvP Icon Scale = "PvP Icon Scale"
 How the graphical counter should be displayed = "How the graphical counter should be displayed"
 Background alpha for bars OOC and target accuired (takes precedence over Not Full) = "Background alpha for bars OOC and target acquired (takes precedence over Not Full)"
 Predefined settings for different bars = "Predefined settings for different bars"
 Click to open IceHUD options. = "Click to open IceHUD options."
 Right Tag = "Right Tag"
 PvP Icon Vertical Offset = "PvP Icon Vertical Offset"
 With this enabled, the raid icon is always 100% alpha, regardless of the bar's alpha. Otherwise, it assumes the bar's alpha level. = "With this enabled, the raid icon is always 100% alpha, regardless of the bar's alpha. Otherwise, it assumes the bar's alpha level."
 Presets = "Presets"
 Bar Alpha = "Bar Alpha"
 Lacerate Cou

**Comment by MelchiorGaspar** [comment]
1x IceHUD/IceHUD.lua:421: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@IceHUD/IceHUD.lua"]:421: in main chunk

Locals:
L = <table> {
 If your class power is not full (or not empty in the case of Holy Power) then the module will always be displayed on your screen using the In Combat alpha setting. Otherwise it will fade to the OOC alpha when you leave combat. = "If your class power is not full (or not empty in the case of Holy Power) then the module will always be displayed on your screen using the In Combat alpha setting. Otherwise it will fade to the OOC alpha when you leave combat."
 Bar vertical offset = "Bar vertical offset"
 When the player is in one of the chosen shapeshift forms the bar will be shown, otherwise it will be hidden. = "When the player is in one of the chosen shapeshift forms the bar will be shown, otherwise it will be hidden."
 This will hide the entire mod when interacting with a barbershop. = "This will hide the entire mod when interacting with a barbershop."
 Show Minimap Icon = "Show Minimap Icon"
 Sets the height of this module. = "Sets the height of this module."
 Item to track = "Item to track"
 No decoration = "No decoration"
 Potential SnD time bar alpha = "Potential SnD time bar alpha"
 Determines the bar width compared to the whole texture width = "Determines the bar width compared to the whole texture width"
 Whether or not to show incoming heals as a lighter-colored bar on top of your current health (requires LibHealComm-4.0 or official patch 4.0) = "Whether or not to show incoming heals as a lighter-colored bar on top of your current health (requires LibHealComm-4.0 or official patch 4.0)"
 Buffs / row = "Buffs / row"
 Flash when ready = "Flash when ready"
 Only show in groups = "Only show in groups"
 Self Display Mode = "Self Display Mode"
 Module type: = "Module type:"
 Debuff grow direction = "Debuff grow direction"
 What this bar should do whenever the player is the TargetOfTarget = "What this bar should do whenever the player is the TargetOfTarget"
 Change color when not in range = "Change color when not in range"
 Raid Icon X Offset = "Raid Icon X Offset"
 BG Alpha in combat = "BG Alpha in combat"
 Controls which direction the bar fills up. With this checked, the bar will fill opposite from normal (e.g. for health: 0% at the top, 100% at the bottom). = "Controls which direction the bar fills up. With this checked, the bar will fill opposite from normal (e.g. for health: 0% at the top, 100% at the bottom)."
 Contextual Background = "Contextual Background"
 Lower text visible = "Lower text visible"
 Pulse when full = "Pulse when full"
 Debuff horizontal offset = "Debuff horizontal offset"
 Icon Settings = "Icon Settings"
 IceHUD Bar Texture = "IceHUD Bar Texture"
 Font = "Font"
 DogTag-formatted string to use for the right side of the bar.

Type /dogtag for a list of available tags.

Remember to press Accept after filling out this box or it will not save. = "DogTag-formatted string to use for the right side of the bar.

Type /dogtag for a list of available tags.

Remember to press Accept after filling out this box or it will not save."
 Settings related to positioning and alpha = "Settings related to positioning and alpha"
 Hides Blizzard Player frame and disables all events related to it = "Hides Blizzard Player frame and disables all events related to it"
 PvP Icon Scale = "PvP Icon Scale"
 How the graphical counter should be displayed = "How the graphical counter should be displayed"
 Background alpha for bars OOC and target accuired (takes precedence over Not Full) = "Background alpha for bars OOC and target acquired (takes precedence over Not Full)"
 Predefined settings for different bars = "Predefined settings for different bars"
 Click to open IceHUD options. = "Click to open IceHUD options."
 Right Tag = "Right Tag"
 PvP Icon Vertical Offset = "PvP Icon Vertical Offset"
 With this enabled, the raid icon is always 100% alpha, regardless of the bar's alpha. Otherwise, it assumes the bar's alpha level. = "With this enabled, the raid icon is always 100% alpha, regardless of the bar's alpha. Otherwise, it assumes the bar's alpha level."
 Presets = "Presets"
 Bar Alpha = "Bar Alpha"
 Lacerate Cou

**Comment by MelchiorGaspar** [comment]
1x ...bs/LibDogTag-Unit-3.0/Categories/Characteristics.lua:176: attempt to compare nil with number
[string "@IceHUD/libs/LibDogTag-Unit-3.0/Categories/Characteristics.lua"]:176: in function `v'
[string "@IceHUD/libs/LibDogTag-Unit-3.0/Cleanup.lua"]:42: in main chunk

Locals:
DogTag_Unit = <table> {
 IsNormalUnit = <table> {
 }
 IsLegitimateUnit = <table> {
 }
 frame = Frame {
 }
 UnitToLocale = <table> {
 }
 L = <table> {
 }
}
DogTag = <table> {
 callbackToFunction = <table> {
 }
 callbackToExtraArg = <table> {
 }
 __colors = <table> {
 }
 Tags = <table> {
 }
 codeToFunction = <table> {
 }
 TimerHandlers = <table> {
 }
 kwargsToKwargTypesWithTableCache = <table> {
 }
 EventHandlers = <table> {
 }
 frame = Frame {
 }
 fixNamespaceList = <table> {
 }
 fsToFrame = <table> {
 }
 compilationSteps = <table> {
 }
 kwargsToKwargTypes = <table> {
 }
 usedEvents = <table> {
 }
 UnitToLocale = <table> {
 }
 IsLegitimateUnit = <table> {
 }
 IsNormalUnit = <table> {
 }
 eventData = <table> {
 }
 callbackToKwargTypes = <table> {
 }
 callbackToCode = <table> {
 }
 fsToCode = <table> {
 }
 codeEvaluationTime = <table> {
 }
 fsToNSList = <table> {
 }
 unpackNamespaceList = <table> {
 }
 L = <table> {
 }
 fsToKwargs = <table> {
 }
 codeToEventList = <table> {
 }
 fsNeedQuickUpdate = <table> {
 }
 fsNeedUpdate = <table> {
 }
 callbackToKwargs = <table> {
 }
 callbackToNSList = <table> {
 }
 AddonFinders = <table> {
 }
 callback_num = 0
}
L = <table> {
 Return the current or last spell to be cast = "Return the current or last spell to be cast"
 Curse = "Curse"
 Resting = "Resting"
 Tauren_short = "Ta"
 Dead = "Dead"
 Draenei = "Draenei"
 Gnome_female = "Gnome"
 Characteristics = "Characteristics"
 Return True if the unit has a Poison debuff = "Return True if the unit has a Poison debuff"
 %s's %s = "%s's %s"
 Warlock = "Warlock"
 Troll_short = "Tr"
 Human = "Human"
 Flight_short = "Fl"
 Boss_short = "b"
 Cat_short = "Ca"
 Party member #%d = "Party member #%d"
 Return the shapeshift form the unit is in if unit is a druid = "Return the shapeshift form the unit is in if unit is a druid"
 Target = "Target"
 Draenei_short = "Dr"
 Priest_female = "Priest"
 DND = "DND"
 Mage_short = "Ma"
 Return True if friendly unit is has a debuff of type = "Return True if friendly unit is has a debuff of type"
 Blood Elf = "Blood Elf"
 Return the number of seconds the current cast has been delayed by interruption = "Return the number of seconds the current cast has been delayed by interruption"
 Gnome = "Gnome"
 Mage_female = "Mage"
 Paladin_short = "Pa"
 Return True if the unit is stealthed in some way = "Return True if the unit is stealthed in some way"
 Shaman_short = "Sh"
 Stealthed = "Stealthed"
 Combat = "Combat"
 Poison = "Poison"
 Hunter_female = "Hunter"
 Return the name of unit, appending unit's realm if different from yours = "Return the name of unit, appending unit's realm if different from yours"
 %s's pet = "%s's pet"
 Troll_female = "Troll"
 Return True if unit has the aura argument = "Return True if unit has the aura argument"
 Druid_short = "Dr"
 Tauren_female = "Tauren"
 Travel = "Travel"
 Dwarf_female = "Dwarf"
 Return True if the current cast is a channeling spell = "Return True if the current cast is a channeling spell"
 Rogue_female = "Rogue"
 Paladin_female = "Paladin"
 Return True if the unit has a Magic debuff = "Return True if the unit has a Magic debuff"
 Boss = "Boss"
 Night Elf = "Night Elf"
 Orc_short = "Or"
 Runic Power = "Runic Power"
 Death Knight_short = "DK"
 Tapped = "Tapped"
 Raid member #%d = "Raid member #%d"
 Orc_female = "Orc"
 Mouse-over = "Mouse-over"
 Holy Light = "Holy Light"
 Mana = "Mana"
 Troll = "Troll"
 Return True if the unit has the Shield Wall buff = "Return True if the unit has the Shield Wall buff"
 Aquatic = "Aquatic"
 Vehicle = "Vehicle"
 Rogue_short = "Ro"
 Rage = "Rage"
 Soulstoned = "Soulstoned"
 Shaman = "Shaman"
 Mage = "Mage"
 Dwarf = "Dwarf"
 Online = "Online"
 Blood Elf_short = "BE"
 Shaman_female = "Shaman"
 Return True if unit is an enemy = "Return True if unit is an enemy"
 Human_short = "Hu"
 Return True if the level of unit is %d = "Return True if the level of unit is %d"
 Blood Elf_female = "Blood Elf"
 Return the level of unit = "Return the level of unit"
 Warlock_short = "Wl"
 Return the realm of unit if not your own realm = "Return the realm of unit if not y

**Comment by MelchiorGaspar** [comment]
I hope that is all the errors I found in the Bug Sack for IceHUD..

**Comment by parnic** [comment]
Which version of IceHUD? This should all already be fixed in 1.15.0

**Comment by MelchiorGaspar** [comment]
oops sry for not reporting the version..
I am still using v1.14.42 
sry I will check again for updates to addons.

**Comment by MelchiorGaspar** [comment]
ooh ok that is why I didn't see the update to IceHUD,
its a alpha build I am set to release builds.. I will install and reload.

**Comment by parnic** [comment]
I don't know if Curse has gotten through its 11.0 backlog or not, but you can grab the release from GitHub instead if you want

**Comment by MelchiorGaspar** [comment]
I installed via the CurseForge standalone Windows client I use.

**Comment by MelchiorGaspar** [comment]
its seems to have cleared up the errors 
ty so much for a quick reply and info.
this is one of my favorite WoW addons. :D
