### ISSUE TITLE
classic config not operational

### ISSUE THREAD

**Issue by godfeast** [parnic/ice-hud#6]
i installed icehud AND the ace3 libraries BUT, even though the hud shows up in game and functions, if i attempt to /icehud nothing happens and if i click to open the icehud config from the button it just clickcs and also does nothing.

How can i help you locate this bug/error so i can use the hud config?

**Comment by parnic** [comment]
IceHUD works fine for me in Classic.

Enable only IceHUD by itself (no other mods) and see if everything works. If it does, enable a few mods at a time until you isolate which one is causing the conflict with IceHUD. If you have VuhDo installed, make sure it's at the latest version; previous versions caused conflicts with other mods like IceHUD.

If you want to be more technical about it, use the `/console scriptErrors 1` command to enable Lua errors in the Classic client, then reload your UI.

Reopen this issue if you identify a problem with IceHUD itself.
