### ISSUE TITLE
classic: no de/buff timers / durations

### ISSUE THREAD

**Issue by apptum** [parnic/ice-hud#9]
Not sure if this is a bug or a missing dependency but it doesn't show any timer / durations (for example Huntersmark: a timer ticking backwards from "2:00").
When in "configuration mode" there are numbers ticking down on all the buff/debuff icons though.
Then I installed weakAuras and Ellipsis it suddenly worked! Strange thing is, when I disable even one of them, it stops working again... any idea?

- yes, tested if the bugs the same if iceHud is the only addon
- I'm on classic
- no difference if DogTag is enabled.

**Comment by apptum** [comment]
First I tried installing LibClassicDurations, but that didn't work. After installing ClassicAuraDurations durations are finally shown.

**Comment by parnic** [comment]
Yes, the mod optionanally supports that classic library for buff durations. The classic game client does not provide this information, so the library is a best-guess at durations. For that reason, I don't include the library with the mod, but do support it if the user already has it.

**Comment by apptum** [comment]
ok, thanks for clarification. But you could mention that anywhere, for classic it looks like a bug (especially with the timers showing in config mode)

**Comment by parnic** [comment]
I don't intend on including a note about that because it's how the Classic client works, it's not the mod's fault. I appreciate the feedback, though.
